name: "Checkout recursively with submodules"
description: "Installs tt-metal extra dev dependencies on ubuntu-20.04 GitHub Actions runners"

inputs:
  token:
    description: "Token with which to do the checkout"
    required: true
    default: ${{ github.token }}
  fetch-depth:
    description: "Fetch depth for checkout"
    required: true
    default: 1

runs:
  using: "composite"
  steps:
    - name: Clean repo (if it exists)
      shell: bash
      run: |
        if [ -d ".git" ]; then
          git clean -xffd
          find .git -type f -iname '*.lock' -delete
          git submodule deinit -f --all
        fi
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}
        fetch-depth: ${{ inputs.fetch-depth }}
        lfs: false
        submodules: recursive
        clean: true
    - name: Clean each submodule
      shell: bash
      run: git submodule foreach 'git clean -xffd'
