name: "[internal] Python wheels test impl"

on:
  workflow_call:
    inputs:
      from-precompiled:
        description: "Use precompiled assets for wheel build"
        default: True
        type: boolean

# Since pre-compiled assets are only built on ubuntu-20.04, we force tests
# to only be run on ubuntu-20.04.
#
# Otherwise, we run across 20.04 and 22.04 as we should have assets for both
# from previous wheel builds if from-precompiled is false.
#
# I chose the more heavy-handed approach because:
# - This should all go away soon once we have more OSes + more Docker up and
# running so we can matrix properly across more stuff
# - though provides less flexibility to caller workflows, we want to be pretty
# strict with the matrix + doesn't change often

jobs:
  test-wheels-host:
    strategy:
      matrix:
        os: ${{ fromJson(inputs.from-precompiled && '["ubuntu-20.04"]' || '["ubuntu-20.04", "ubuntu-22.04"]') }}
        runner-hw-info: [
          {arch: grayskull},
          {arch: wormhole_b0}
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-metal-deps
        with:
          os: ${{ matrix.os }}
      - uses: actions/download-artifact@v4
        with:
          name: eager-dist-${{ matrix.os }}-any
      - name: Set up end-to-end tests environment
        run: ./tests/scripts/set_up_end_to_end_tests_env.sh
      - name: Activate env and run release tests - host
        shell: bash
        run: |
          source tests/end_to_end_tests/env/bin/activate
          cd tests/end_to_end_tests
          pytest -c conftest.py . -m eager_host_side
  test-wheels-silicon:
    strategy:
      matrix:
        # We only have this for non-Docker silicon runners right now
        os: [ubuntu-20.04]
        runner-hw-info: [
          {arch: grayskull, type: E150},
          {arch: wormhole_b0, type: N150},
          {arch: wormhole_b0, type: N300}
        ]
    runs-on: ["cloud-virtual-machine", "${{ matrix.runner-hw-info.type }}", "in-service"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: eager-dist-${{ matrix.os }}-any
      - name: Set up end-to-end tests environment
        run: ./tests/scripts/set_up_end_to_end_tests_env.sh
      - name: Activate env and run release tests - silicon
        timeout-minutes: 2
        shell: bash
        run: |
          source tests/end_to_end_tests/env/bin/activate
          python3 -m ttnn.examples.usage.run_op_on_device
          cd tests/end_to_end_tests
          pytest -c conftest.py . -m eager_package_silicon
