name: "Blackhole post-commit tests"

on:
  workflow_call:
    inputs:
      runner-label:
          description: 'Optional: BH'
          required: false
          type: string
          default: 'BH'
  workflow_dispatch:
    inputs:
      runner-label:
          description: 'Optional: BH'
          required: true
          type: string
          default: 'BH'
  schedule:
    - cron: "0 */2 * * *"
  # Pause this since not enough runners to support every commit to main
  # push:
  #  branches: ["main"]

permissions:
  actions: read
  contents: write
  pull-requests: write
  pages: write
  id-token: write
  packages: write

jobs:
  static-checks:
    uses: ./.github/workflows/all-static-checks.yaml
    secrets: inherit
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      os: "ubuntu-22.04-amd64"
  build-wheels:
    needs: build-artifact
    uses: ./.github/workflows/_build-wheels-impl.yaml
    with:
      os: "ubuntu-22.04"
      from-precompiled: true
  umd-unit-tests:
    secrets: inherit
    uses: ./.github/workflows/umd-unit-tests.yaml
    with:
      arch: blackhole
      runner-label: ${{ inputs.runner-label || 'BH' }}
  sd-unit-tests:
    needs: build-artifact
    uses: ./.github/workflows/build-and-unit-tests.yaml
    secrets: inherit
    with:
      arch: blackhole
      runner-label: ${{ inputs.runner-label || 'BH' }}
      timeout: 30
      os: "ubuntu-22.04"
  fd-unit-tests:
    needs: build-wheels
    uses: ./.github/workflows/fast-dispatch-build-and-unit-tests.yaml
    secrets: inherit
    with:
      arch: blackhole
      runner-label: ${{ inputs.runner-label || 'BH' }}
      os: "ubuntu-22.04"
  # FD C++ Unit Tests
  cpp-unit-tests:
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/cpp-post-commit.yaml
    with:
      arch: blackhole
      runner-label: ${{ inputs.runner-label || 'BH' }}
      timeout: 60
      os: "ubuntu-22.04"

#   profiler-regression:
#     needs: build-artifact-profiler
#     uses: ./.github/workflows/run-profiler-regression.yaml
#     secrets: inherit
#   build-and-test-wheels:
#     uses: Check all-post-commit yaml for directions
#     secrets: inherit
#   build-docs:
#     needs: build-artifact
#     uses: ./.github/workflows/docs-latest-public.yaml
#     secrets: inherit
#   build:
#     uses: ./.github/workflows/build.yaml
#     secrets: inherit
  # We used to use this for post-commit, but we didn't have enough runners
  # to support the number of developers running this workflow
  # build-and-test-measure-perf:
  # build-and-test-measure-perf-device:
