name: "[deprecated] Build TT-Metalium across all configs"

on:
  workflow_call:
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  pages: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
