name: "Build TT-Metalium across all configs"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  ubuntu-2004-debug:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      os: "ubuntu-20.04-amd64"
      toolchain: "cmake/x86_64-linux-clang-17-libcpp-toolchain.cmake"
      build-type: "Debug"
      publish-artifact: false

  ubuntu-2004-relwithdebinfo:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      os: "ubuntu-20.04-amd64"
      toolchain: "cmake/x86_64-linux-clang-17-libcpp-toolchain.cmake"
      build-type: "RelWithDebInfo"
      publish-artifact: false

  ubuntu-2204-release:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      os: "ubuntu-22.04-amd64"
      toolchain: "cmake/x86_64-linux-clang-17-libcpp-toolchain.cmake"
      build-type: "Release"
      publish-artifact: false

  ubuntu-2204-libstdcpp:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      os: "ubuntu-22.04-amd64"
      toolchain: "cmake/x86_64-linux-clang-17-libstdcpp-toolchain.cmake"
      build-type: "Release"
      publish-artifact: false
      skip-tt-train: true

  ubuntu-2204-gcc12:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      os: "ubuntu-22.04-amd64"
      toolchain: "cmake/x86_64-linux-gcc-12-toolchain.cmake"
      build-type: "Release"
      publish-artifact: false
      skip-tt-train: true # FIXME
