name: "[internal] Nightly fast dispatch tests impl"

on:
  workflow_call:

jobs:
  fd-nightly:
    strategy:
      # Do not fail-fast because we need to ensure all tests go to completion
      # so we try not to get hanging machines
      fail-fast: false
      matrix:
        test-group:
          [
            {
              name: "Common models GS",
              arch: grayskull,
              runs-on: ["cloud-virtual-machine", "E150", "in-service"],
              cmd: tests/scripts/single_card/nightly/run_common_models.sh,
              timeout: 40
            },
            {
              name: "GS ttnn nightly",
              arch: grayskull,
              runs-on: ["cloud-virtual-machine", "E150", "in-service"],
              cmd: tests/scripts/single_card/nightly/run_ttnn.sh,
              timeout: 40
            },
            {
              name: "WH N150 ttnn nightly",
              arch: wormhole_b0,
              runs-on: ["cloud-virtual-machine", "N150", "in-service"],
              cmd: tests/scripts/single_card/nightly/run_ttnn.sh,
              timeout: 70
            },
            {
              name: "WH N300 ttnn nightly",
              arch: wormhole_b0,
              runs-on: ["cloud-virtual-machine", "N300", "in-service"],
              cmd: tests/scripts/single_card/nightly/run_ttnn.sh,
              timeout: 70
            },
            {
              name: "GS-only models",
              arch: grayskull,
              runs-on: ["cloud-virtual-machine", "E150", "in-service"],
              cmd: tests/scripts/single_card/nightly/run_gs_only.sh,
              timeout: 40
            },
          ]
    name: FD ${{ matrix.test-group.name }} ${{ matrix.test-group.arch }}
    env:
      ARCH_NAME: ${{ matrix.test-group.arch }}
      LOGURU_LEVEL: INFO
      LD_LIBRARY_PATH: ${{ github.workspace }}/build/lib
    runs-on: ${{ matrix.test-group.runs-on }}
    steps:
      - uses: tenstorrent/tt-metal/.github/actions/checkout-with-submodule-lfs@main
      - uses: ./.github/actions/retry-command
        with:
          timeout-seconds: 100
          max-retries: 10
          backoff-seconds: 60
          command: ./.github/scripts/cloud_utils/mount_weka.sh
      - name: Set up dyanmic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - uses: ./.github/actions/prepare-metal-run
      - uses: ./.github/actions/install-python-deps
      - name: Run frequent reg tests scripts
        timeout-minutes: ${{ matrix.test-group.timeout }}
        run: |
          source ${{ github.workspace }}/python_env/bin/activate
          cd $TT_METAL_HOME
          export PYTHONPATH=$TT_METAL_HOME
          ${{ matrix.test-group.cmd }}
      - uses: ./.github/actions/upload-artifact-with-job-uuid
        if: ${{ !cancelled() }}
        with:
          path: |
            generated/test_reports/
          prefix: "test_reports_"
  nightly-wh-models:
    strategy:
      # Do not fail-fast because we need to ensure all tests go to completion
      # so we try not to get hanging machines
      fail-fast: false
      matrix:
        card: [N150, N300]
        model: [common_models, functional_unet, llama3.2-1B, qwen, mistral7b, mistral7b_eth, resnet50, yolov4]
    name: Nightly ${{ matrix.card }} ${{ matrix.model }}
    env:
      ARCH_NAME: wormhole_b0
      LOGURU_LEVEL: INFO
      LD_LIBRARY_PATH: ${{ github.workspace }}/build/lib
    runs-on: ["cloud-virtual-machine", "in-service", "${{ matrix.card }}"]
    steps:
      - uses: tenstorrent/tt-metal/.github/actions/checkout-with-submodule-lfs@main
      - uses: ./.github/actions/retry-command
        with:
          timeout-seconds: 100
          max-retries: 10
          backoff-seconds: 60
          command: ./.github/scripts/cloud_utils/mount_weka.sh
      - name: Set up dyanmic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - name: Set up WH_ARCH_YAML for eth-enabled models
        if: ${{ matrix.model != 'mistral7b' }}
        run: |
          echo "WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml" >> $GITHUB_ENV
      - uses: ./.github/actions/prepare-metal-run
      - uses: ./.github/actions/install-python-deps
      - name: Run frequent reg tests scripts
        timeout-minutes: 30
        # Llama3 has a single pytest for multiple llama models, hence it requires calling it multiple times.
        # Due to host OOM issues in CI vm, we currently only run llama-1B in the model matrix.
        run: |
          source ${{ github.workspace }}/python_env/bin/activate
          cd $TT_METAL_HOME
          export PYTHONPATH=$TT_METAL_HOME
          if [[ "${{ matrix.model }}" == *"llama3"* ]]; then
            pytest -n auto tests/nightly/single_card/llama3 -k ${{ matrix.model }}
          fi
            if [[ "${{ matrix.model }}" != *"llama3"* ]]; then
            pytest -n auto tests/nightly/single_card/${{ matrix.model }}
          fi
      - uses: ./.github/actions/upload-artifact-with-job-uuid
        if: ${{ !cancelled() }}
        with:
          path: |
            generated/test_reports/
          prefix: "test_reports_"
  nightly-wh-unstable-models:
    strategy:
      # Do not fail-fast because we need to ensure all tests go to completion
      # so we try not to get hanging machines
      fail-fast: false
      matrix:
        test-config:
          - model: "stable_diffusion"
            cmd: pytest --timeout 900 -n auto tests/nightly/single_card/stable_diffusion
              # Skipping due to issue #15932
              # - model: "mamba 1"
              # cmd: pytest --timeout 900 -n auto tests/nightly/single_card/mamba --splits 6 --group 1
              # - model: "mamba 2"
              # cmd: pytest --timeout 900 -n auto tests/nightly/single_card/mamba --splits 6 --group 2
              # - model: "mamba 3"
              # cmd: pytest --timeout 900 -n auto tests/nightly/single_card/mamba --splits 6 --group 3
              # - model: "mamba 4"
              # cmd: pytest --timeout 900 -n auto tests/nightly/single_card/mamba --splits 6 --group 4
          - model: "mamba 5"
            cmd: pytest --timeout 900 -n auto tests/nightly/single_card/mamba --splits 6 --group 5
              # - model: "mamba 6"
              # cmd: pytest --timeout 900 -n auto tests/nightly/single_card/mamba --splits 6 --group 6
        card: [N150, N300]
    name: "[Unstable] Nightly ${{ matrix.card }} ${{ matrix.test-config.model }}"
    env:
      ARCH_NAME: wormhole_b0
      LOGURU_LEVEL: INFO
      LD_LIBRARY_PATH: ${{ github.workspace }}/build/lib
    runs-on: ["cloud-virtual-machine", "in-service", "${{ matrix.card }}"]
    steps:
      - uses: tenstorrent-metal/metal-workflows/.github/actions/checkout-with-submodule-lfs@v2.0.0
      - uses: ./.github/actions/retry-command
        with:
          timeout-seconds: 100
          max-retries: 10
          backoff-seconds: 60
          command: ./.github/scripts/cloud_utils/mount_weka.sh
      - name: Set up dyanmic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - name: Set up WH_ARCH_YAML for eth-enabled models
        run: |
          echo "WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml" >> $GITHUB_ENV
      - uses: ./.github/actions/prepare-metal-run
      - uses: ./.github/actions/install-python-deps
      - name: Run frequent reg tests scripts
        timeout-minutes: 60
        run: |
          source ${{ github.workspace }}/python_env/bin/activate
          cd $TT_METAL_HOME
          export PYTHONPATH=$TT_METAL_HOME
          ${{ matrix.test-config.cmd }}
      - uses: ./.github/actions/upload-artifact-with-job-uuid
        if: ${{ !cancelled() }}
        with:
          path: |
            generated/test_reports/
          prefix: "test_reports_"
