name: "[internal] Fast dispatch frequent tests impl"

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: "ubuntu-20.04"

jobs:
  fd-frequent:
    strategy:
      # Do not fail-fast because we need to ensure all tests go to completion
      # so we try not to get hanging machines
      fail-fast: false
      matrix:
        test-group:
          - name: "WH N300 pgm dispatch nightly"
            arch: wormhole_b0
            runs-on: ["cloud-virtual-machine", "N300", "in-service"]
            run-args: |
              ./build/test/tt_metal/perf_microbenchmark/dispatch/test_pgm_dispatch_wormhole_b0 --benchmark_out_format=json --benchmark_out=bench.json
              ./tests/tt_metal/tt_metal/perf_microbenchmark/dispatch/compare_pgm_dispatch_perf_ci.py bench.json
            timeout: 10
    name: ${{ matrix.test-group.name }}
    env:
      LOGURU_LEVEL: INFO
    runs-on: ${{ matrix.test-group.runs-on }}
    steps:
      - uses: tenstorrent/tt-metal/.github/actions/checkout-with-submodule-lfs@main
      - uses: ./.github/actions/prepare-metal-run
      - name: ${{ matrix.test-group.name }} tests
        timeout-minutes: ${{ matrix.test-group.timeout }}
        uses: ./.github/actions/docker-run
        with:
          docker_os_arch: tt-metalium/${{ inputs.os }}-amd64
          docker_password: ${{ secrets.GITHUB_TOKEN }}
          docker_opts: |
            -e TT_METAL_HOME=${{ github.workspace }}
            -e ARCH_NAME=${{ matrix.test-group.arch }}
            -e LD_LIBRARY_PATH=${{ github.workspace }}/build/lib
          run_args: ${{ matrix.test-group.run-args }}
      - uses: ./.github/actions/slack-report
        if: ${{ failure() }}
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          owner: U01Q0T3J3D0 # Paul Keller
      - uses: ./.github/actions/upload-artifact-with-job-uuid
        if: ${{ !cancelled() }}
        with:
          path: |
            generated/test_reports/
          prefix: "test_reports_"
      - uses: ./.github/actions/upload-artifact-with-job-uuid
        if: ${{ !cancelled() }}
        with:
          path: |
            bench.json
          prefix: "pgm_benchmarks_json_"
