name: "(Single-card) Tests for new models"

on:
  workflow_dispatch:
    inputs:
      build-type:
        required: false
        default: Release
        type: choice
        options:
          - Release
          - Debug
          - RelWithDebInfo
          - CI

permissions:
  actions: read
  contents: write
  pull-requests: write
  pages: write
  id-token: write
  packages: write

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      build-type: ${{ inputs.build-type || 'Release' }}
  build-artifact-profiler:
    uses: ./.github/workflows/build-artifact.yaml
    with:
      tracy: true
      build-type: ${{ inputs.build-type || 'Release' }}
    secrets: inherit
  device-perf-single-card:
    needs: build-artifact-profiler
    uses: ./.github/workflows/perf-device-models-impl.yaml
    secrets: inherit
  e2e-model-perf-single-card:
    needs: build-artifact
    uses: ./.github/workflows/perf-models-impl.yaml
    secrets: inherit
  nightly-single-card:
    needs: build-artifact
    uses: ./.github/workflows/fast-dispatch-full-regressions-and-models-impl.yaml
    secrets: inherit
  demos-single-card:
    needs: build-artifact
    uses: ./.github/workflows/single-card-demo-tests-impl.yaml
    secrets: inherit
