name: "[post-commit] models tests"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  static-checks:
    uses: ./.github/workflows/all-static-checks.yaml
    secrets: inherit
  build-docker-artifact:
    uses: ./.github/workflows/build-docker-artifact.yaml
    secrets: inherit
  build-artifact:
    needs: build-docker-artifact
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  build-wheels:
    needs: build-artifact
    strategy:
      matrix:
        # Since pre-compiled builds only run on 20.04, we can only test on 20.04 for now
        # The full 22.04 flow can be tested without precompiled
        os: [ubuntu-20.04]
    uses: ./.github/workflows/_build-wheels-impl.yaml
    with:
      os: ${{ matrix.os }}
      from-precompiled: true
    secrets: inherit
  models-unit-tests:
    needs: build-wheels
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          { arch: grayskull, runner-label: E150 },
          { arch: wormhole_b0, runner-label: N150 },
          { arch: wormhole_b0, runner-label: N300 },
        ]
    uses: ./.github/workflows/models-post-commit.yaml
    with:
      arch: ${{ matrix.test-group.arch}}
      runner-label: ${{ matrix.test-group.runner-label}}
