name: "Create and Publish Release Docker Image"

on:
  workflow_dispatch:
jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  build-wheels:
    needs: build-artifact
    strategy:
      matrix:
        # Since pre-compiled builds only run on 20.04, we can only test on 20.04 for now
        # The full 22.04 flow can be tested without precompiled
        os: [ubuntu-20.04]
    uses: ./.github/workflows/_build-wheels-impl.yaml
    with:
      os: ${{ matrix.os }}
      from-precompiled: true
  publish-release-image:
    needs: build-wheels
    uses: ./.github/workflows/publish-release-image.yaml
    secrets: inherit
    with:
      version: dev-${GITHUB_REF_NAME//\//-}
      is_major_version: false
