name: "[internal] T3000 perplexity tests impl"

on:
  workflow_call:

jobs:

  t3000-accuracy-perplexity-tests:
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          { name: "t3k_falcon7b_tests", arch: wormhole_b0, cmd: run_t3000_falcon7b_perplexity_tests, timeout: 300, owner_id: U05RWH3QUPM}, # Salar Hosseini
          { name: "t3k_falcon40b_tests", arch: wormhole_b0, cmd: run_t3000_falcon40b_perplexity_tests, timeout: 300, owner_id: U053W15B6JF}, # Djordje Ivanovic
          { name: "t3k_llama_70b_tests", arch: wormhole_b0, cmd: run_t3000_llama70b_perplexity_tests, timeout: 300, owner_id: U03FJB5TM5Y}, # Colman Glagovich
          { name: "t3k_mixtral_tests", arch: wormhole_b0, cmd: run_t3000_mixtral8x7b_perplexity_tests, timeout: 300, owner_id: U03PUAKE719}, # Miguel Tairum
          { name: "t3k_llama3_tests_single_card", arch: wormhole_b0, cmd: run_t3000_llama3_perplexity_tests_single_card, timeout: 300, owner_id: U03PUAKE719}, # Mark O'Connor
          { name: "t3k_llama3_tests_t3k", arch: wormhole_b0, cmd: run_t3000_llama3_perplexity_tests_t3000, timeout: 300, owner_id: U03PUAKE719}, # Mark O'Connor
        ]

    name: ${{ matrix.test-group.name }}
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.test-group.arch }}
      LOGURU_LEVEL: INFO
      LD_LIBRARY_PATH: ${{ github.workspace }}/build/lib
    environment: dev
    runs-on: ["arch-wormhole_b0", "config-t3000", "in-service", "pipeline-perf"]
    steps:
      - uses: tenstorrent/tt-metal/.github/actions/checkout-with-submodule-lfs@main
      - uses: ./.github/actions/ensure-active-weka-mount
      - name: Set up dynamic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - uses: actions/download-artifact@v4
        with:
          name: TTMetal_build_any
      - name: Extract files
        run: tar -xvf ttm_any.tar
      - uses: ./.github/actions/install-python-deps
      - name: Run perplexity tests
        shell: bash {0}
        timeout-minutes: ${{ matrix.test-group.timeout }}
        run: |
          source ${{ github.workspace }}/python_env/bin/activate
          cd $TT_METAL_HOME
          export PYTHONPATH=$TT_METAL_HOME
          source ${{ github.workspace }}/tests/scripts/t3000/run_t3000_perplexity_tests.sh
          ${{ matrix.test-group.cmd }}
      - uses: ./.github/actions/slack-report
        if: ${{ failure() }}
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          owner: ${{ matrix.test-group.owner_id }}
