name: "(T3K) T3000 frequent tests"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *" # This cron schedule runs the workflow every 8 hours

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  t3000-frequent-tests:
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/t3000-frequent-tests-impl.yaml
