name: "(T3K) T3000 unit tests"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *" # This cron schedule runs the workflow every 3 hours

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  t3000-unit-tests:
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/t3000-unit-tests-impl.yaml
