name: "[internal] T3000 profiler tests impl"

on:
  workflow_call:
    inputs:
      extra-tag:
        required: false
        type: string
        default: "in-service"

jobs:
  t3000-profiler-tests:
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          {
            name: "T3000 profiler tests",
            arch: wormhole_b0,
            runs-on: ["arch-wormhole_b0", "config-t3000", "pipeline-perf", "${{ inputs.extra-tag }}"],
            cmd: './tests/scripts/run_profiler_regressions.sh'
          },
        ]
    name: ${{ matrix.test-group.name }}
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.test-group.arch }}
      LOGURU_LEVEL: INFO
      LD_LIBRARY_PATH: ${{ github.workspace }}/build/lib
    runs-on: ${{ matrix.test-group.runs-on }}
    steps:
      - uses: tenstorrent/tt-metal/.github/actions/checkout-with-submodule-lfs@main
      - name: Set up dynamic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - uses: actions/download-artifact@v4
        with:
          name: TTMetal_build_any_profiler
      - name: Extract files
        run: tar -xvf ttm_any.tar
      - uses: ./.github/actions/install-python-deps
      - name: Run profiler regression tests
        timeout-minutes: 30
        run: |
          ./tests/scripts/run_profiler_regressions.sh
      - uses: ./.github/actions/slack-report
        if: ${{ failure() }}
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          owner: U03BJ1L3LUQ # Mo Memarian
