name: "(T3K) T3000 demo tests"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1,3,5' # This cron schedule runs the workflow every Monday/Wednesday/Friday at 12am UTC
  workflow_call:

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  t3000-demo-tests:
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/t3000-demo-tests-impl.yaml
