name: "(TG) TG demo tests"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1,3,5' # This cron schedule runs the workflow every Monday/Wednesday/Friday at 12am UTC

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  tg-demo-tests:
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/tg-demo-tests-impl.yaml
