name: "(TG) TG model perf tests"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *" # This cron schedule runs the workflow every 12 hours

jobs:
  build-artifact-profiler:
    uses: ./.github/workflows/build-artifact.yaml
    with:
      tracy: true
    secrets: inherit
  tg-model-perf-tests:
    needs: build-artifact-profiler
    secrets: inherit
    uses: ./.github/workflows/tg-model-perf-tests-impl.yaml
