name: "(TGG) TGG frequent tests"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *" # This cron schedule runs the workflow every 8 hours

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  tgg-frequent-tests:
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/tgg-frequent-tests-impl.yaml
