name: "(TGG) TGG model perf tests"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *" # This cron schedule runs the workflow every 12 hours

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  tgg-model-perf-tests:
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/tgg-model-perf-tests-impl.yaml
