name: "[internal] tt-train C++ tests impl"

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      runner-label:
        required: true
        type: string
      timeout:
        required: false
        type: number
        default: 20
  workflow_dispatch:
    inputs:
      arch:
        required: true
        type: choice
        options:
          - wormhole_b0
      runner-label:
        required: true
        type: choice
        options:
          - N150
          - N300
      timeout:
        required: false
        type: number
        default: 20

jobs:
  models:
    strategy:
      # Do not fail-fast because we need to ensure all tests go to completion
      # so we try not to get hanging machines
      fail-fast: false
      matrix:
        test-group: [
          {name: tt-train, cmd: ctest --no-tests=error --output-on-failure},
        ]
    name: ${{ matrix.test-group.name }} ${{ inputs.arch }} ${{ inputs.runner-label }}
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ inputs.arch }}
      LOGURU_LEVEL: INFO
      LD_LIBRARY_PATH: ${{ github.workspace }}/build/lib
      TEST_DATA_DIR: ${{ github.workspace }}/data
      ENABLE_CI_ONLY_TT_TRAIN_TESTS: 1
    runs-on:
      - ${{ inputs.runner-label }}
      - cloud-virtual-machine
      - in-service
    steps:
      - uses: tenstorrent/tt-metal/.github/actions/checkout-with-submodule-lfs@main
      - name: Set up dynamic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - uses: ./.github/actions/prepare-metal-run
      - name: ${{ matrix.test-group.name }} tests
        timeout-minutes: ${{ inputs.timeout }}
        run: |
          source ${{ github.workspace }}/python_env/bin/activate
          export PYTHONPATH=$TT_METAL_HOME
          cd $TT_METAL_HOME
          cp ./build/tt-train/3rd_party/wandb-cpp/libwandbcpp.so build/lib/
          find ./build -type f -name "*.tcl" -o -name "*.cmake" -exec sed -i "s|/home/ubuntu/[^/]*/_work/tt-metal/tt-metal/build_Release|${TT_METAL_HOME}/build|g" {} +
          cd $TT_METAL_HOME/build/tt-train
          ldd tests/ttml_tests || true
          ${{ matrix.test-group.cmd }}
      - uses: ./.github/actions/slack-report
        if: ${{ failure() }}
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          owner: U07ASPTGJTS # Denys
      - name: Generate system logs on failure
        uses: ./.github/actions/generate-system-logs
        if: ${{ failure() }}
